name: Build and Deploy NuGet Package

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-build -o out

    - name: Deploy
      run: dotnet nuget push artifacts/Release/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      with:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}